default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maceta_development

test:
  <<: *default
  database: maceta_test

production:
  <<: *default
  database: maceta_production
  username: maceta
  password: <%= ENV['MACETA_DATABASE_PASSWORD'] %>
