# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d97d2c7173a744c02ad393d10ef0d687bbf903b45e6c809c14bb09941e270e0eb1cee1aec93650d708bfae1737f6828be5cfc581265db0ea7e14e83d2f42d08d

test:
  secret_key_base: 436c4d9f5c9cb43c0f85cc04a1ef2af6d7c9f4c8573e29cd555b6c2f5e4630e0be3a8c4d6382ce63532ad11bd3329a5ed9667f9845d2f705a4655808bd81344d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
